# Site Settings
title: DYNOMIGHT
tagline: a blog
email: email@email.com
description: "science and existential angst"
baseurl: "/"
url: "https://dynomight.net"
#permalink: pretty
permalink: none
twitter:
  username: dynomight7
social:
  name: dynomight
  links:
    - https://twitter.com/dynomight7
author:
    name: dynomight
    url: https://dynomight.net/
    twitter: dynomight7

paginate: 100
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: /img/deathvalley/small.jpg
      show_sidebar: true

      #image: /img/deathvalleysky_nps_big.jpg

feed:
  posts_limit: 30